### ISSUE TITLE
TypeError upon load

### ISSUE THREAD

**Issue by twstagg** [klaxa/OCR-Manga#8]
» trohrt » [OCR-Manga]: ./Reader.py berserk.[mh].c001.cbz 
Traceback (most recent call last):
  File "./Reader.py", line 383, in <module>
    main()
  File "./Reader.py", line 379, in main
    app.update_screen()
  File "./Reader.py", line 150, in update_screen
    self.change_image(0)
  File "./Reader.py", line 245, in change_image
    image = self.best_fit(width, height, image)
TypeError: best_fit() takes 3 positional arguments but 4 were given

**Comment by klaxa** [comment]
Whoops, looks like someone (me) didn't test stuff before merging. Will take
a look at it when I'm home.

**Comment by twstagg** [comment]
@klaxa I made a pull request fixing it, just merge
